# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  host: 127.0.0.1

development:
  <<: *default
  database: xkcd_development
  username: postgres
  password: password

production:
  url: <%= ENV["DATABASE_URL"] %>
